

  [build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/Exp2.1.html"
  status = 200

[[redirects]]
  from = "/Exp2.1"
  to = "/Exp2.1.html"
  status = 200

[[redirects]]
  from = "/Exp2.2"
  to = "/Exp2.2.html"
  status = 200

[[redirects]]
  from = "/Exp2.3"
  to = "/Exp2.3.html"
  status = 200
